#+title: psci-mode
#+author: ardumont

At the moment, not everything works.
For example, the `:r` command (which is supposed to reset the loaded modules of the current session) does nothing (but it does work in a terminal session).

* Description
** What

Major mode for [[http://www.purescript.org/][purescript]]'s repl psci.

** How

Based on comint.
Following this tutorial http://www.masteringemacs.org/article/comint-writing-command-interpreter.

** Why

The [[https://github.com/dysinger/purescript-mode][purescript-mode]] (forked from [[https://github.com/haskell/haskell-mode][haskell-mode]]) does not provide any repl integration (yet?).
The experience inside the terminal is somewhat tedious at the moment.
So I thought of giving it a shot.

** When

How about now?

** Who

[[https://github.com/ardumont][me]]!

* Install

As soon as something is working, I intend to release on melpa/melpa-stable/marmalade.

For the moment, clone the repository, add to load-path and eval the buffer psci.el.

** Start

#+begin_src sh
M-x psci/run
#+end_src

** Setup

I encounter (thanks to @purcell) a simple mode that I quite like which is called [[https://github.com/tomterl/repl-toggle][repl-toggle]].
This permits, using the same universal binding, to go back and forth between the repl and the buffer.

#+begin_src emacs-lisp
(require 'repl-toggle)
(require 'psci)
(add-to-list 'rtog/mode-repl-alist '(purescript-mode . psci/run))
#+end_src

Now, using `C-c C-z` binding inside a purescript buffer, this will switch on a psci buffer.
And inside a psci buffer, this same binding will get back inside the purescript buffer you are coming from.
